<?php
/**
 * Page "Theme Wizard".
 *
 * @author Ondřej Doněk, <ondrejd@gmail.com>
 * @package odwp-devhelper
 * @since 0.0.1
 */
?><div class="wrap">

	<?php screen_icon(); ?>

	<h2>
		<?php _e( 'Theme Wizard', DevHelper::SLUG ); ?>
		<small><?php _e( 'Generator for WordPress themes.', DevHelper::SLUG ); ?></small>
	</h2>

	<form id="theme-wizard">
		<table class="form-table">
			<!-- Advanced options -->
			<?php echo $wizard->render_advanced_options( $display_description ); ?>
		</table>
		<!-- Submit buttons -->
		<?php echo $wizard->render_submit_buttons(); ?>
	</form>
</div>
