<?php
/**
 * WordPress theme wizard.
 *
 * @author Ondřej Doněk, <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-devhelper for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-devhelper
 * @since 0.0.1
 */

if( ! defined( 'ABSPATH' ) ) {
  exit;
}

/**
 * @var string $form_url
 */
$form_url = admin_url( 'edit.php?post_type=' . DevHelper_Wizard_CustomPostType::SLUG . '&page=' . $wizard->slug );

?><div class="wrap">
	<h1 class="wp-heading-inline"><?php _e( 'Wizards - WordPress Theme', DH_SLUG )?></h1>
    <hr class="wp-header-end">
	<p class="description"><?php printf(
		__( 'Generate required minimal source codes for quicker development of new %1$sWordPress%2$s themes.', DH_SLUG ),
		'<a href="https://wordpress.org/" target="blank">',
		'</a>'
	); ?></p>
	<form id="theme-wizard" action="<?php esc_attr_e( $form_url )?>" method="post">
		<table class="form-table">
			<tbody>
				<!-- Advanced options -->
				<?php echo $wizard->render_advanced_options( $show_description, 'theme', $wizard->template->get_values() ); ?>
			</tbody>
		</table>
		<!-- Submit buttons -->
		<?php echo $wizard->render_submit_buttons(); ?>
	</form>
</div>
