<?php
/**
 * Page "Plugin wizard".
 *
 * @author Ondřej Doněk, <ondrejd@gmail.com>
 * @package odwp-devhelper
 * @since 0.0.1
 */
?><div class="wrap">

	<?php screen_icon(); ?>

	<h2>
		<?php _e( 'Plugin Wizard', DevHelper::SLUG ); ?>
		<small><?php _e( 'Generator for WordPress plugins.', DevHelper::SLUG ); ?></small>
	</h2>

	<form id="plugin-wizard">
		<table class="form-table">
			<tbody>
				<!-- Name -->
				<tr>
					<th scope="row">
						<label for="plugin-name"><?php _e( 'Name', DevHelper::SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p>
								<input type="text" name="plugin-name" id="plugin-name" class="regular-text" placeholder="<?php _e( 'Enter name of your plugin', DevHelper::SLUG ) ?>">
							</p>
						</fieldset>
					</td>
				</tr>
				<!-- Identifier -->
				<tr>
					<th scope="row">
						<label for="plugin-identifier"><?php _e( 'Identifier', DevHelper::SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p>
								<input type="text" name="plugin-identifier" id="plugin-identifier" class="regular-text" placeholder="<?php _e( 'Enter identifier of your plugin', DevHelper::SLUG ) ?>">
							</p>
							<p class="description"><?php _e( '<b>Identifier</b> could be derrived from plugin\'s name and can NOT contains spaces, tabs and other control or special characters.', DevHelper::SLUG ) ?></p>
						</fieldset>
					</td>
				</tr>
				<!-- Description -->
				<tr>
					<th scope="row">
						<label for="plugin-description"><?php _e( 'Description', DevHelper::SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p>
								<label for="plugin-description"><?php _e( 'Short description:', DevHelper::SLUG ) ?></label><br>
								<textarea name="plugin-description" id="plugin-description" class="long-text" placeholder="<?php _e( 'Enter short description of your plugin', DevHelper::SLUG ) ?>" cols="72" rows="5"></textarea>
							</p>
							<p>
								<label for="plugin-description_full"><?php _e( 'Full description:', DevHelper::SLUG ) ?></label><br>
								<textarea name="plugin-description_full" id="plugin-description_full" class="long-text" placeholder="<?php _e( 'Enter full description of your plugin', DevHelper::SLUG ) ?>" cols="72" rows="10"></textarea>
							</p>
							<p class="description"><?php _e( 'Both descriptions are used in <code>readme.txt</code> file.', DevHelper::SLUG ) ?></p>
						</fieldset>
					</td>
				</tr>
				<!-- Tags -->
				<tr>
					<th scope="row">
						<label for="plugin-tags"><?php _e( 'Tags', DevHelper::SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p><?php _e( 'Enter list of tags separated by comma.', DevHelper::SLUG ) ?></p>
							<p>
								<input type="text" name="plugin-tags" id="plugin-tags" class="regular-text" placeholder="<?php _e( 'Enter comma separated list of tags', DevHelper::SLUG ) ?>" style="width: 695px;">
							</p>
							<p class="description"><?php _e( 'For example: <code>red,black,blue</code>.', DevHelper::SLUG ) ?></p>
						</fieldset>
					</td>
				</tr>
				<!-- Version -->
				<tr>
					<th scope="row">
						<label for="plugin-version"><?php _e( 'Version', DevHelper::SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p><?php _e( 'Enter current version of the plugin, minimal required <b>WordPress</b> version, maximal version of <b>WordPress</b> on which was plugin tested and plugin\'s version which is considered to be stable.', DevHelper::SLUG ) ?></p>
							<p>
								<label for="plugin-version" style="width: 130px;"><?php _e( 'Current version:', DevHelper::SLUG ) ?></label>
								<input type="text" name="plugin-version" id="plugin-version" style="width: 120px;">
							</p>
							<p>
								<label for="plugin-required_at_least" style="width: 130px;"><?php _e( 'Required at least:', DevHelper::SLUG ) ?></label>
								<input type="text" name="plugin-required_at_least" id="plugin-required_at_least" style="width: 120px;">
							</p>
							<p>
								<label for="plugin-tested_up_to" style="width: 130px;"><?php _e( 'Tested up to:', DevHelper::SLUG ) ?></label>
								<input type="text" name="plugin-tested_up_to" id="plugin-tested_up_to" style="width: 120px;">
							</p>
							<p>
								<label for="plugin-stable_tag" style="width: 130px;"><?php _e( 'Stable tag:', DevHelper::SLUG ) ?></label>
								<input type="text" name="plugin-stable_tag" id="plugin-stable_tag" style="width: 120px;">
							</p>
							<p class="description"><?php _e( 'Some valid versions as an example: <b>3.4.0</b>, <b>4.4</b>, <b>1.2.1</b> etc.', DevHelper::SLUG ) ?></p>
						</fieldset>
					</td>
				</tr>
				<!-- Author -->
				<tr>
					<th scope="row">
						<label for="plugin-author"><?php _e( 'Author', DevHelper::SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p><?php _e( 'Enter author\'s name and valid homepage\'s URL.', DevHelper::SLUG ) ?></p>
							<p>
								<label for="plugin-author" style="width: 130px;"><?php _e( 'Author:', DevHelper::SLUG ) ?></label>
								<input type="text" name="plugin-author" id="plugin-author" class="regular-text" placeholder="<?php _e( 'Enter author\'s name', DevHelper::SLUG ) ?>">
							</p>
							<p>
								<label for="plugin-author_uri" style="width: 130px;"><?php _e( 'URI:', DevHelper::SLUG ) ?></label>
								<input type="text" name="plugin-author_uri" id="plugin-author_uri" class="regular-text" placeholder="<?php _e( 'Enter URI of author\'s homepage', DevHelper::SLUG ) ?>">
							</p>
						</fieldset>
					</td>
				</tr>
				<!-- Contributors -->
				<tr>
					<th scope="row">
						<label for="plugin-contributors"><?php _e( 'Contributors', DevHelper::SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p><?= sprintf( __( 'Comma separated list of contributors.', DevHelper::SLUG ), '<a href="https://wordpress.org/" target="blank">', '</a>' ) ?></p>
							<p>
								<input type="text" name="plugin-contributors" id="plugin-contributors" class="regular-text" placeholder="<?php _e( 'Enter comma separated list of contributors', DevHelper::SLUG ) ?>" style="width: 695px;">
							</p>
							<p class="description"><?php _e( 'For example: <code>joed,jimb,janed</code>.', DevHelper::SLUG ) ?></p>
						</fieldset>
					</td>
				</tr>
				<!-- License -->
				<tr>
					<th scope="row">
						<label for="plugin-author"><?php _e( 'License', DevHelper::SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<legend>
								<span><?php _e( 'Either select or enter name of license and its URL. You can also select no license but it is not recommended.', DevHelper::SLUG ) ?></span>
							</legend>
							<div>
								<label title="<?php _e( 'No license', DevHelper::SLUG ) ?>" class="license">
									<input type="radio" name="plugin-license" value="none" checked="checked">
									<?php _e( 'No license', DevHelper::SLUG ) ?>
								</label>
							</div>
							<div>
								<label title="<?php _e( 'Selected license', DevHelper::SLUG ) ?>" class="license">
								<input type="radio" name="plugin-license" value="custom">
								<?php _e( 'Selected:', DevHelper::SLUG ) ?>
								<div style="padding-left: 25px;" class="license_custom">
									<div class="inputs-subarea">
										<span class="screen-reader-text"><?php _e( 'select license', DevHelper::SLUG ) ?></span>
										<label class="screen-reader-text" for="plugin-license_select"><?php _e( 'Licenses', DevHelper::SLUG ) ?></label>
										<select name="plugin-license_select" id="plugin-license_select" disabled="disabled">
											<option value="Apache License 2.0" data-license_url="http://www.apache.org/licenses/LICENSE-2.0">Apache License 2.0</option>
											<option value="GPL 2.0" data-license_url="http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt">GPL v2</option>
											<option value="GPL 3.0" data-license_url="http://www.gnu.org/licenses/gpl-3.0.txt">GPL v3</option>
											<option value="MPL 2.0" data-license_url="https://www.mozilla.org/MPL/2.0/">MPL 2.0</option>
											<option value="MIT License" data-license_url="https://opensource.org/licenses/MIT">MIT License</option>
										</select>
									</div>
								</div>
							</div>
							<div>
								<label title="<?php _e( 'Custom license', DevHelper::SLUG ) ?>" class="license">
								<input type="radio" name="plugin-license" value="other">
								<?php _e( 'Custom license:', DevHelper::SLUG ) ?>
								<div style="padding-left: 25px;" class="license_other">
									<div class="inputs-subarea">
										<p>
											<label for="plugin-license_other_name" style="width: 130px;"><?php _e( 'Name:', DevHelper::SLUG ) ?></label>
											<input type="text" name="plugin-license_other_name" id="plugin-license_other_name" class="regular-text" placeholder="<?php _e( 'Enter license\'s name', DevHelper::SLUG ) ?>" disabled="disabled">
										</p>
										<p>
											<label for="plugin-license_other_uri" style="width: 130px;"><?php _e( 'URI:', DevHelper::SLUG ) ?></label>
											<input type="text" name="plugin-license_other_uri" id="plugin-license_other_uri" class="regular-text" placeholder="<?php _e( 'Enter URI of license', DevHelper::SLUG ) ?>" disabled="disabled">
										</p>
										<p class="description"><?php _e( 'For example: <code>Mozilla Public License 2.0</code> and <code>https://www.mozilla.org/MPL/2.0/</code>.', DevHelper::SLUG ) ?></p>
									</div>
								</div>
							</div>
						</fieldset>
					</td>
				</tr>
				<!-- Donate Link -->
				<tr>
					<th scope="row">
						<label for="plugin-donate_link"><?php _e( 'Donate Link', DevHelper::SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p><?php _e( 'Valid URL of link with donation page. Leave blank if you don\'t have one.', DevHelper::SLUG ) ?></p>
							<p>
								<input type="text" name="plugin-donate_link" id="plugin-donate_link" class="regular-text" placeholder="<?php _e( 'Enter donate link', DevHelper::SLUG ) ?>" style="width: 695px;">
							</p>
						</fieldset>
					</td>
				</tr>
				<!-- Installation -->
				<tr>
					<th scope="row">
						<label for="plugin-installation"><?php _e( 'Installation', DevHelper::SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p>
								<label for="plugin-installation"><?php _e( 'Installation instructions:', DevHelper::SLUG ) ?></label><br>
								<textarea name="plugin-installation" id="plugin-installation" class="long-text" placeholder="<?php _e( 'Enter plugin installation instructions', DevHelper::SLUG ) ?>" cols="72" rows="10"><?= WP_Style_Guide::get_option( 'default_install_text' ) ?></textarea>
							</p>
							<p class="description"><?php _e( 'Installation instructions are part of <code>readme.txt</code> file.', DevHelper::SLUG ) ?></p>
						</fieldset>
					</td>
				</tr>
				<!-- FAQ -->
				<tr>
					<th scope="row">
						<label for="plugin-faq"><?php _e( 'FAQ', DevHelper::SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p>
								<label for="plugin-faq"><?php _e( 'Frequently asked questions:', DevHelper::SLUG ) ?></label><br>
								<textarea name="plugin-faq" id="plugin-faq" class="long-text" placeholder="<?php _e( 'Enter frequently asked questions', DevHelper::SLUG ) ?>" cols="72" rows="10"><?= WP_Style_Guide::get_option( 'default_faq_text' ) ?></textarea>
							</p>
							<p class="description"><?php _e( 'Frequently asked questions are part of <code>readme.txt</code> file.', DevHelper::SLUG ) ?></p>
						</fieldset>
					</td>
				</tr>
				<!-- TODO Screenshots -->
				<!-- Change Log -->
				<tr>
					<th scope="row">
						<label for="plugin-changelog"><?php _e( 'Change Log', DevHelper::SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p>
								<textarea name="plugin-changelog" id="plugin-changelog" class="long-text" placeholder="<?php _e( 'Enter change log of your plugin' ) ?>" cols="72" rows="10"><?= WP_Style_Guide::get_option( 'default_changelog_text' ) ?></textarea>
							</p>
							<p class="description"><?php _e( 'Change log is a part of <code>readme.txt</code> file.', DevHelper::SLUG ) ?></p>
						</fieldset>
					</td>
				</tr>
				<!-- Upgrade notice -->
				<tr>
					<th scope="row">
						<label for="plugin-upgrade"><?php _e( 'Upgrade notice', DevHelper::SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p>
								<textarea name="plugin-upgrade" id="plugin-upgrade" class="long-text" placeholder="<?php _e( 'Enter upgrade notice', DevHelper::SLUG ) ?>" cols="72" rows="10"></textarea>
							</p>
							<p class="description"><?php _e( 'Upgrade notice is a part of <code>readme.txt</code> file. When starting new plugin this field will be probably empty.', DevHelper::SLUG ) ?></p>
						</fieldset>
					</td>
				</tr>
				<!-- Options -->
				<tr>
					<th scope="row">
						<label for="plugin-has_dependency"><?php _e( 'Options', DevHelper::SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<legend class="screen-reader-text"><?php _e( 'Other plugin options', DevHelper::SLUG ) ?></legend>
							<p>
								<label for="plugin-include_license_file">
									<input type="checkbox" id="plugin-include_license_file" name="plugin-include_license_file" <?= checked( ( bool ) WP_Style_Guide::get_option( 'default_include_license_file' ) ) ?>>
									<span><?php _e( 'Include license in a standalone file', DevHelper::SLUG ) ?></span>
								</label>
							</p>
							<p>
								<label for="plugin-has_dependency">
									<input type="checkbox" id="plugin-has_dependency" name="plugin-has_dependency" <?= checked( ( bool ) WP_Style_Guide::get_option( 'default_has_dependency' ) ) ?>>
									<span><?php _e( 'Plugin has dependency to other plugin(s)', DevHelper::SLUG ) ?></span>
								</label>
							</p>
							<p>
								<label for="plugin-has_administration">
									<input type="checkbox" id="plugin-has_administration" name="plugin-has_administration" <?= checked( ( bool ) WP_Style_Guide::get_option( 'default_has_administration' ) ) ?>>
									<span><?php _e( 'Plugin contains administration', DevHelper::SLUG ) ?></span>
								</label>
							</p>
							<!-- TODO This checkbox need `plugin-has_administration` checked! -->
							<p>
								<label for="plugin-has_options">
									<input type="checkbox" id="plugin-has_options" name="plugin-has_options" <?= checked( ( bool ) WP_Style_Guide::get_option( 'default_has_options' ) ) ?>>
									<span><?php _e( 'Plugin has options (will be included new options page into WordPress administration)', DevHelper::SLUG ) ?></span>
								</label>
							</p>
							<p>
								<label for="plugin-has_own_dbtables">
									<input type="checkbox" id="plugin-has_own_dbtables" name="plugin-has_own_dbtables" <?= checked( ( bool ) WP_Style_Guide::get_option( 'default_has_own_dbtables' ) ) ?>>
									<span><?php _e( 'Plugin has own database tables', DevHelper::SLUG ) ?></span>
								</label>
							</p>
							<p>
								<label for="plugin-has_localization">
									<input type="checkbox" id="plugin-has_localization" name="plugin-has_localization" <?= checked( ( bool ) WP_Style_Guide::get_option( 'default_has_localization' ) ) ?>>
									<span><?php _e( 'Plugin will be localized (create <code>languages</code> folder with <code>POT</code> file)', DevHelper::SLUG ) ?></span>
								</label>
							</p>
						</fieldset>
					</td>
				</tr>
				<!-- Template -->
				<tr>
					<th scope="row">
						<label for="plugin-template"><?php _e( 'Template', DevHelper::SLUG ) ?></label>
					</th>
					<td>
						<p style="color: #f30;"><code>XXX</code> &ndash; Finish this!</p>
						<fieldset>
							<legend><?php _e( 'Select template for generating plugin source codes' ) ?></legend>
							<div>
								<label title="<?php _e( 'Default template', DevHelper::SLUG ) ?>" class="default">
									<input type="radio" name="plugin-template" value="none" checked="checked">
									<?php _e( 'Default template', DevHelper::SLUG ) ?>
								</label>
							</div>
							<div>
								<label title="<?php _e( 'WordPress Plugin Boilerplate by Devin Devinson', DevHelper::SLUG ) ?>" class="default">
									<input type="radio" name="plugin-template" value="none" checked="checked">
									<?= sprintf( __( '<a href="%s" target="blank">WordPress Plugin Boilerplate</a> by <a href="%s" target="blank">Devin Devinson</a>', DevHelper::SLUG ), '', '' ) ?>
								</label>
							</div>
						</fieldset>
					</td>
				</tr>
				<!-- Advanced options -->
				<?php echo odwpdh_render_advanced_options_form( $slug, $display_description ); ?>
			</tbody>
		</table>
		<!-- Submit buttons -->
		<?php echo odwpdh_render_form_submit_buttons( $slug ); ?>
	</form>
</div>
