<div class="wrap">

	<?php screen_icon(); ?>

	<h1><?= __( 'Wizards - WordPress Widget', WP_Style_Guide::PLUGIN_SLUG )?></h1>

	<p class="description">
		<?php sprintf( __( 'Generate new <a href="%s" target="blank">widgets</a> (using <a href="%s" target="blank">Widget API</a>).', WP_Style_Guide::PLUGIN_SLUG ), 'https://codex.wordpress.org/WordPress_Widgets', 'https://codex.wordpress.org/Widgets_API' ); ?>
	</p>

	<form id="wizard-dashboard_widget">
		<table class="form-table">
			<tbody>
				<!-- Name -->
				<tr>
					<th scope="row">
						<label for="widget-classname"><?= __( 'Class name', WP_Style_Guide::PLUGIN_SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p>
								<input type="text" name="plugin-classname" id="plugin-classname" class="regular-text" placeholder="<?= __( 'My_Widget', WP_Style_Guide::PLUGIN_SLUG ) ?>">
							</p>
							<p class="description"><?php printf( __( 'Name of class which will extends <a href="%s" target="blank"><code>WP_Widget</code></a>', WP_Style_Guide::PLUGIN_SLUG ), 'https://developer.wordpress.org/reference/classes/wp_widget/' ); ?></p>
						</fieldset>
					</td>
				</tr>
				<!-- Identifier -->
				<tr>
					<th scope="row">
						<label for="plugin-identifier"><?= __( 'Identifier', WP_Style_Guide::PLUGIN_SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p>
								<input type="text" name="plugin-identifier" id="plugin-identifier" class="regular-text" placeholder="<?= __( 'Enter identifier of your plugin', WP_Style_Guide::PLUGIN_SLUG ) ?>">
							</p>
							<p class="description"><?= __( '<b>Identifier</b> could be derrived from plugin\'s name and can NOT contains spaces, tabs and other control or special characters.', WP_Style_Guide::PLUGIN_SLUG ) ?></p>
						</fieldset>
					</td>
				</tr>
				<!-- Description -->
				<tr>
					<th scope="row">
						<label for="plugin-description"><?= __( 'Description', WP_Style_Guide::PLUGIN_SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p>
								<label for="plugin-description"><?= __( 'Short description:', WP_Style_Guide::PLUGIN_SLUG ) ?></label><br>
								<textarea name="plugin-description" id="plugin-description" class="long-text" placeholder="<?= __( 'Enter short description of your plugin', WP_Style_Guide::PLUGIN_SLUG ) ?>" cols="72" rows="5"></textarea>
							</p>
							<p>
								<label for="plugin-description_full"><?= __( 'Full description:', WP_Style_Guide::PLUGIN_SLUG ) ?></label><br>
								<textarea name="plugin-description_full" id="plugin-description_full" class="long-text" placeholder="<?= __( 'Enter full description of your plugin', WP_Style_Guide::PLUGIN_SLUG ) ?>" cols="72" rows="10"></textarea>
							</p>
							<p class="description"><?= __( 'Both descriptions are used in <code>readme.txt</code> file.', WP_Style_Guide::PLUGIN_SLUG ) ?></p>
						</fieldset>
					</td>
				</tr>
				<!-- Advanced options -->
				<?php echo $wizard->render_advanced_options( $display_description ); ?>
            </tbody>
		</table>
        <!-- Submit buttons -->
        <?php echo $wizard->render_submit_buttons(); ?>
	</form>

	<hr>

	<p class="description"><?php _e( 'Below are generated files that are required to get working WordPress plugin with new widget. You can copy source codes to clipboard or download it as a ZIP package.<br>You can also test these source files before using them.', DevHelper::SLUG ); ?></p>

	<!-- TODO Here should be rendered generated PHP source -->
	<h3><code><?php echo 'my-example-list/includes/class-my_example_widget.php'; ?></code></h3>
	<pre><code class="language-php">&lt;?php
/**
 * File description ...
 *
 * @package my-example-widget
 * @since 1.0
 */

if ( ! class_exists( 'My_Widget' ) ):

/**
 * Class description ...
 *
 * @see WP_Widget
 * @since 1.0
 */
class My_Widget extends WP_Widget {
    // ...
} // End of My_Widget

endif;

</code></pre>
</div>