<?php
/**
 * Widget wizard.
 *
 * @author Ondřej Doněk, <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-devhelper for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-devhelper
 * @since 0.0.1
 */

if( ! defined( 'ABSPATH' ) ) {
  exit;
}

/**
 * @var string $form_url
 */
$form_url = admin_url( 'edit.php?post_type=' . DevHelper_Wizard_CustomPostType::SLUG . '&page=' . $wizard->slug );

?><div class="wrap">
	<h1 class="wp-heading-inline"><?php _e( 'Wizards - WordPress Widget', DH_SLUG )?></h1>
    <hr class="wp-header-end">
	<p class="description"><?php printf(
		__( 'Generate new %1$swidgets%2$s (using %3$sWidget API%4$s). Generated code contains new class that extends %5$sWP_Widget%6$s class and piece of code needed for activation.', DH_SLUG ),
		'<a href="https://codex.wordpress.org/WordPress_Widgets" target="blank">',
		'</a>',
		'<a href="https://codex.wordpress.org/Widgets_API" target="blank">',
		'</a>',
		'<a href="https://developer.wordpress.org/reference/classes/wp_widget/" target="blank">',
		'</a>'
	)?></p>
	<form id="wizard-dashboard_widget" action="<?php esc_attr_e( $form_url )?>" method="post">
		<table class="form-table">
			<tbody>
				<!-- Class name -->
				<tr>
					<th scope="row">
						<label for="widget-classname"><?php _e( 'Class name', DH_SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p>
								<input type="text" name="classname" id="widget-classname" class="regular-text" placeholder="<?php _e( 'My_Widget', DH_SLUG ) ?>" value="<?php echo $wizard->template->get_value( 'classname' )?>">
							</p>
							<p class="description"><?php printf( __( 'Name of class which will extend <a href="%s" target="blank"><code>WP_Widget</code></a>', DH_SLUG ), 'https://developer.wordpress.org/reference/classes/wp_widget/' ); ?></p>
						</fieldset>
					</td>
				</tr>
				<!-- Title -->
				<tr>
					<th scope="row">
						<label for="widget-title"><?php _e( 'Title', DH_SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p>
								<input type="text" name="title" id="widget-identifier" class="regular-text" placeholder="<?php _e( 'My Widget', DH_SLUG )?>" value="<?php echo $wizard->template->get_value( 'title' )?>">
							</p>
							<p class="description"><?php _e( 'Enter title of your widget.', DH_SLUG ) ?></p>
						</fieldset>
					</td>
				</tr>
				<!-- Description -->
				<tr>
					<th scope="row">
						<label for="widget-description"><?php _e( 'Description', DH_SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p>
								<input type="text" name="description" id="widget-description" class="long-text" placeholder="<?php _e( 'My awesome widget.', DH_SLUG ) ?>" value="<?php echo $wizard->template->get_value( 'description' )?>">
							</p>
							<p class="description"><?php _e( 'Enter short description of your widget.', DH_SLUG ) ?></p>
						</fieldset>
					</td>
				</tr>
				<!-- Has options? -->
				<tr>
					<th scope="row">
						<label for="widget-has_options"><?php _e( 'Has options', DH_SLUG ) ?></label>
					</th>
					<td>
						<fieldset>
							<p>
								<label for="widget-has_options">
									<input type="checkbox" name="has_options" id="widget-has_options" <?php checked( $wizard->template->get_value( 'has_options' ) )?>>
									<?php _e( 'Will your widget provide options?', DH_SLUG ) ?>
								</label>
							</p>
							<p class="description"><?php printf(
								__( 'If checked generated source codes contain also methods <code>%1$s</code> and <code>%2$s</code>.', DH_SLUG ),
								'<a href="https://developer.wordpress.org/reference/classes/wp_widget/form/" target="blank">WP_Widget::Form</a>',
								'<a href="https://developer.wordpress.org/reference/classes/wp_widget/update/" target="blank">WP_Widget::Update</a>'
							) ?></p>
						</fieldset>
					</td>
				</tr>
				<!-- Advanced options -->
				<?php echo $wizard->render_advanced_options( $show_description, 'widget', $wizard->template->get_values() ); ?>
            </tbody>
		</table>
        <!-- Submit buttons -->
        <?php echo $wizard->render_submit_buttons(); ?>
	</form>
	<hr>
	<p class="description"><?php _e( 'Below are generated files that are required to get working WordPress plugin with new widget. You can copy source codes to clipboard or download it as a ZIP package.<br>You can also test these source files before using them.', DH_SLUG ); ?></p>

	<!-- TODO Here should be rendered generated PHP source -->
	<h3><code><?php echo 'my-example-list/includes/class-my_example_widget.php'; ?></code></h3>
	<pre><code class="language-php">&lt;?php
<?php $wizard->template->preview() ?>
</code></pre>
</div>