<?php
/**
 * @author Ondřej Doněk, <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-devhelper for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-devhelper
 * @since 0.1.0
 *
 * Variables passed to the partial:
 * 
 * @var boolean $generate_full_plugin
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<label for="odwpdh_settings_generate_full_plugin">
    <input type="checkbox" id="odwpdh_settings_generate_full_plugin" name="odwpdh_settings[generate_full_plugin]" <?php checked( $generate_full_plugin ) ?>>
    <?php _e( 'Generate always full plugin sources?', DH_SLUG ) ?>
</label>
<p class="description"><?php _e( 'If you check this option all wizards will output source codes which contain fully functional WordPress plugin.', DH_SLUG ) ?></p>