<?php
/**
 * Part of common wizard.
 *
 * @author Ondřej Doněk, <ondrejd@gmail.com>
 * @link https://github.com/ondrejd/odwp-devhelper for the canonical source repository
 * @license https://www.gnu.org/licenses/gpl-3.0.en.html GNU General Public License 3.0
 * @package odwp-devhelper
 * @since 0.0.1
 * 
 * @todo Add spinner and make this works via AJAX (with safe-fall to plain POST and PHP).
 */

if( ! defined( 'ABSPATH' ) ) {
    exit;
}

?>
<input type="submit" name="wizard-submit1" value="<?php esc_attr_e( 'Generate', DH_SLUG ); ?>" title="<?php esc_attr_e( 'Regenerate source codes below.', DH_SLUG )?>" class="button">
<input type="submit" name="wizard-submit2" value="<?php esc_attr_e( 'Save', DH_SLUG ); ?>" title="<?php esc_attr_e( 'Save wizard and clear entered values.', DH_SLUG )?>" class="button button-primary">
<input type="submit" name="wizard-submit3" value="<?php esc_attr_e( 'Test', DH_SLUG ); ?>" title="<?php esc_attr_e( 'Test generated source codes in live WordPress environment.', DH_SLUG )?>" class="button button-disabled" disabled="disabled">
<input type="submit" name="wizard-submit4" value="<?php esc_attr_e( 'Download', DH_SLUG ); ?>" title="<?php esc_attr_e( 'Download ZIP package with generated sources.', DH_SLUG )?>" class="button button-disabled" disabled="disabled">
